version: '3'
services:
  app:
    image: node:14-alpine
    container_name: wellnessway-server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: wellnessway-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
volumes:
  mongo-data:
